# Generated by Django 4.0.3 on 2022-03-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
